### ISSUE TITLE
Preventing Cell Reuse

### ISSUE THREAD

**Issue by DavidGagne** [toddkramer/tutorials#2]
I'm having a problem with my cells being reused, even though I'm resetting them.

I have (for example) nine images I want to load, but I have 24 cells. I'm using "empty" cells to indicate placeholders for future images.

But when I scroll, the "empty" cells get loaded with images from the nine that are there. Any ideas?

**Comment by DavidGagne** [comment]
Disregard with my apologies. There was a bug in my code.

**Comment by toddkramer** [comment]
Thanks for reading the tutorial! Let me know if you have any other questions about it.

**Comment by DavidGagne** [comment]
Dude. Thank _you_ for writing it! It's **by far** the best explanation of how to deal with a UICollectionView I've found.
I have actually just now moved on to part 2 (about decoding) because -- as you predicted -- the synchronous loading of images is now my bottleneck.
